name: Deploy to Preview
on: 
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build_and_preview:
    permissions: 
      actions: write
      checks: write
      pull-requests: write
      deployments: write
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Install and Build
        run: npm ci && npx astro build
      - name: Deploy and Release
        uses: FirebaseExtended/action-hosting-deploy@v1
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FINATANI_WEBSITE }}
          channelId: preview
          projectId: finatani-website
