name: Deploy and Release
on:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3
      - name: Setup Node.js Version
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: Build the App
        run: |
          npm install & npx astro build
      - name: Install Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash
      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          firebase deploy --only hosting --project $FIREBASE_PROJECT_ID --token "$(cat $GOOGLE_APPLICATION_CREDENTIALS)"
