name: Deploy and Release
on:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3
      - name: Setup Node.js Version
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"
      - name: Build the App
        run: npm install & npx astro build
      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          service_account_email: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_EMAIL }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting
